# Array Manipulation Routines

In [3]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [2]:
y = x.reshape((3, 2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [4]:
y = np.reshape(x, 6)
print(y)

[0 1 2 3 4 5]


In [5]:
print(x)

[[0 1 2]
 [3 4 5]]


In [6]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [7]:
print(x)

[[0 1 2]
 [3 4 5]]


In [8]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [9]:
y = x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [10]:
y = x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [4]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [5]:
z = np.stack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [6]:
z = np.stack((x, y), axis = 0 )
print(z)

[[1 2 3]
 [4 5 6]]


In [7]:
z = np.stack((x, y), axis = -1 )
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
z = np.stack((x, y), axis = 1 )
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [10]:
z = np.dstack((x, y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
print(z.shape)

In [11]:
z = np.hstack((x, y))
print(z)

[1 2 3 4 5 6]


In [13]:
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [12]:
print(z.shape)

(6,)


In [14]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [15]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [16]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.94563388 0.87215026 0.98745216 0.61123717]
  [0.58696418 0.96391103 0.7219727  0.21908042]
  [0.79975942 0.14171576 0.41554491 0.06632609]
  [0.35902928 0.4786788  0.85735721 0.55627722]]

 [[0.82315608 0.67828698 0.42777102 0.22694339]
  [0.73428825 0.79407512 0.5943849  0.34990155]
  [0.01305732 0.96330551 0.89409699 0.91433834]
  [0.09555532 0.04464172 0.93429892 0.44714569]]

 [[0.19569412 0.416096   0.80912578 0.88469575]
  [0.75339523 0.55941175 0.26934278 0.82028803]
  [0.3126805  0.49066971 0.25400029 0.59285826]
  [0.46294825 0.71143953 0.66185377 0.3803475 ]]

 [[0.19351398 0.06214274 0.70743504 0.29142655]
  [0.06109163 0.28349311 0.38510561 0.92683458]
  [0.48685971 0.2288     0.62841022 0.41792786]
  [0.46506983 0.40301622 0.42232468 0.16447961]]]


In [17]:
y, z = np.split(x, 2)
print(y, z)

[[[0.94563388 0.87215026 0.98745216 0.61123717]
  [0.58696418 0.96391103 0.7219727  0.21908042]
  [0.79975942 0.14171576 0.41554491 0.06632609]
  [0.35902928 0.4786788  0.85735721 0.55627722]]

 [[0.82315608 0.67828698 0.42777102 0.22694339]
  [0.73428825 0.79407512 0.5943849  0.34990155]
  [0.01305732 0.96330551 0.89409699 0.91433834]
  [0.09555532 0.04464172 0.93429892 0.44714569]]] [[[0.19569412 0.416096   0.80912578 0.88469575]
  [0.75339523 0.55941175 0.26934278 0.82028803]
  [0.3126805  0.49066971 0.25400029 0.59285826]
  [0.46294825 0.71143953 0.66185377 0.3803475 ]]

 [[0.19351398 0.06214274 0.70743504 0.29142655]
  [0.06109163 0.28349311 0.38510561 0.92683458]
  [0.48685971 0.2288     0.62841022 0.41792786]
  [0.46506983 0.40301622 0.42232468 0.16447961]]]


In [ ]:
y, z = np.dsplit(x, 2)
print(y, z)

In [ ]:
y, z = np.hsplit(x, 2)
print(y, z)

In [ ]:
y, z = np.vsplit(x, 2)
print(y, z)

In [18]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [20]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [21]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [22]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [23]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [24]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [25]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
